// <auto-generated />
using BarCodeScannerApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarCodeScannerApi.Migrations
{
    [DbContext(typeof(BarcodeContext))]
    [Migration("20251112201000_Add description column")]
    partial class Adddescriptioncolumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("BarCodeScannerApi.Data.Models.Item", b =>
                {
                    b.Property<long>("EAN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("ean");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("brand");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("weight");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("color");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Dimension")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("dimension");

                    b.PrimitiveCollection<string>("Images")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("images");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("model");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("size");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("title");

                    b.Property<long>("UPC")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("upc");

                    b.HasKey("EAN");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
